### ISSUE TITLE
Could you update to alpha 4 please?

### ISSUE THREAD

**Issue by enormousrodent** [SardiusMedia/sardius-fullcalendar-wrapper#2]
Is there any way you could upgrade this to alpha .4 from the current .2?

**Comment by joshuaRuff** [comment]
Yes, I’ll work on getting that update this next week 👍

**Comment by enormousrodent** [comment]
Thank you!  If you can update your NPM package too that would be amazing :)

**Comment by joshuaRuff** [comment]
Now using version 4.0.0-alpha.4, and npm package has been updated.

**Comment by enormousrodent** [comment]
Thanks for this!  out of interest.  How would you integrate the scheduler plugin into this manually without you having to import it yourself?

**Comment by flyfishMT** [comment]
Hi, are you interested in updating again? Following fullcalendar's documentation - [https://fullcalendar.io/docs/v4/release-notes](https://fullcalendar.io/docs/v4/release-notes) - this is how I installed the latest:  

`npm install --save @fullcalendar/core @fullcalendar/daygrid
`
which gives me this in my package.json - 

```
    "@fullcalendar/core": "^4.0.0-beta.4",
    "@fullcalendar/daygrid": "^4.0.0-beta.4",
```

This is interesting because the latest release I can see they have on github is beta.2.
Anyways, not sure how this plays with your wrapper.  Thanks!
